E24I/TOGEDOG

.gitignore

pr 템플릿과 브랜치 승인 테스트를 하기 위함입니다
- gitignore에 README.md항목 추가
- 템플릿 작동 잘 됩니다. 승인 부탁드립니다!

:memo: docs: 문서 수정

---

server/src/main/java/togedog/server/domain/alarm/entity/Alarm.java
server/src/main/java/togedog/server/domain/alram/entity/Alram.java
server/src/main/java/togedog/server/domain/chatreport/entity/ChatReport.java
server/src/main/java/togedog/server/domain/chatroom/entity/ChatRoom.java
server/src/main/java/togedog/server/domain/comment/entity/Comment.java
server/src/main/java/togedog/server/domain/commentreport/entity/CommentReport.java
server/src/main/java/togedog/server/domain/feed/entity/Feed.java
server/src/main/java/togedog/server/domain/feedlike/entity/FeedLike.java
server/src/main/java/togedog/server/domain/join/entity/Join.java
server/src/main/java/togedog/server/domain/member/entity/Member.java
server/src/main/java/togedog/server/domain/member/entity/Role.java
server/src/main/java/togedog/server/domain/memberreport/entity/MemberReport.java
server/src/main/java/togedog/server/domain/message/entity/Message.java
server/src/main/java/togedog/server/domain/pet/entity/Gender.java
server/src/main/java/togedog/server/domain/pet/entity/Pet.java
server/src/main/java/togedog/server/domain/reply/entity/Reply.java
server/src/main/java/togedog/server/domain/replylike/entity/ReplyLike.java
server/src/main/java/togedog/server/domain/replyreport/entity/ReplyReport.java
server/src/main/java/togedog/server/global/entity/BaseEnum.java
server/src/main/java/togedog/server/global/entity/State.java
server/src/main/java/togedog/server/global/entity/UserState.java
server/src/test/java/togedog/server/ServerApplicationTests.java

[BE] 도메인별 Entity Column 작성

---

.idea/.gitignore
.idea/TOGEDOG.iml
.idea/compiler.xml
.idea/gradle.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/modules.xml
.idea/modules/server.main.iml
.idea/uiDesigner.xml
.idea/vcs.xml
server/build.gradle
server/src/docs/asciidoc/index.adoc
server/src/main/java/togedog/server/domain/alarm/controller/AlarmController.java
server/src/main/java/togedog/server/domain/alarm/dto/AlarmDto.java
server/src/main/java/togedog/server/domain/alarm/entity/Alarm.java
server/src/main/java/togedog/server/domain/alarm/service/AlarmService.java
server/src/test/java/togedog/server/AlarmControllerTest.java

REST docs 처음 사용해서 간단하게 테스트 해 본 것을 PR합니다 11월 10일(금)에 참고해주세요
Alarm 패키지에 테스트용 controller, dto, service 클래스 추가하였습니다. 추후 수정예정
test에 AlarmControllerTest 클래스 추가하였고 내부 테스트 코드를 참고해주세요
server/src/docs/asciidoc 경로의 index.adoc 파일이 snippets를 모아서 문서화 해줍니다.

:white_check_mark: test: REST docs 테스트를 위한 테스트코드 작성

---

server/build.gradle
server/src/main/java/togedog/server/domain/member/dto/MemberDto.java

build.gradle 에 dependencies 를 추가했습니다.
- validation
- mapstruct
+ 테스트시에 security 적용으로 인한 401error로 security 부분 주석 처리 하였습니다. 
security 부분 개발완료하고 풀어놓겠습니다.

✨ : build.gradle 수정(mapstruct, validation추가)

---

server/src/main/java/togedog/server/domain/member/controller/MemberController.java
server/src/main/java/togedog/server/domain/member/dto/MemberDto.java
server/src/main/java/togedog/server/domain/member/entity/Member.java
server/src/main/java/togedog/server/domain/replylike/entity/ReplyLike.java

- 멤버 DTO가 잘못 PR 되서 수정했습니다. 항상확인하기(메모)

✨ feat : MemberDto 에러 수정

---

client/src/components/loginElement/LoginForm.tsx
client/src/components/loginElement/Oauth.tsx
client/src/components/signUpElement/SignUpForm.tsx
client/src/components/signUpElement/SignUpInputs.tsx
client/src/pages/SignUp.tsx

로그인,회원가입 input 태그 react-hook-form 라이브러리 적용
로그인,회원가입 input 태그 react-hook-form 라이브러리 적용
npm install 해주셔야 할듯 합니다.

:recycle:refactor: input=>react-hook-form 변경

---

client/src/App.tsx
client/src/components/loginElement/LoginForm.style.tsx
client/src/components/loginElement/LoginForm.tsx
client/src/components/loginElement/Oauth.style.tsx
client/src/components/loginElement/Oauth.tsx
client/src/components/myPage/MyFeedForm.tsx
client/src/components/myPage/MyInfoForm.tsx
client/src/components/signUpElement/SignUpForm.style.tsx
client/src/components/signUpElement/SignUpForm.tsx
client/src/components/signUpElement/SignUpInputs.style.tsx
client/src/components/signUpElement/SignUpInputs.tsx
client/src/pages/MyPage.tsx

로그인 기능과 회원가입 기능 구현을 위한 목업을 작업했습니다.
로그인, 회원가입 스타일 파일분리

:sparkles:feat:로그인,회원가입 스타일파일분리

---

client/src/App.tsx
client/src/components/header/Header.tsx
client/src/pages/MapDetail.tsx
client/src/pages/MyMap.tsx
client/src/pages/PetMap.tsx

- 투게독 펫 지도 목업 작성
- 프레임만 생성해 둔 상태입니다.
- `none`

✨ : 투게독 펫 지도 목업 작성

---

client/.gitignore
client/public/index.html
client/src/App.tsx
client/src/components/header/Header.Style.tsx
client/src/components/petFeed/Feed.Style.tsx
client/src/components/petMap/KaKaoMap.tsx
client/src/pages/MapDetail.tsx
client/src/pages/PetMap.tsx

- 펫 지도 피드 상세 페이지 목업 임시 완료
- 컴포넌트 형태를 리스트, 바둑판 형태로 분리 해놨습니다.
- 아직 컴포넌트 분할은 안한 상태고, page 파일 안에 모여있습니다.
- 이후에 펫 지도 api 설정 하겠습니다.

📱: 펫 지도 피드 상세 페이지 목업 임시 완료

---

client/src/components/myPage/MyFeedForm.style.tsx
client/src/components/myPage/MyFeedForm.tsx
client/src/components/myPage/MyInfoForm.style.tsx
client/src/components/myPage/MyInfoForm.tsx
client/src/components/signUpElement/SignUpForm.style.tsx
client/src/components/signUpElement/SignUpForm.tsx
client/src/components/signUpElement/SignUpInputs.style.tsx
client/src/components/signUpElement/SignUpInputs.tsx
client/src/pages/MyPage.tsx

마이페이지 프레임 작업중입니다!
회원가입 페이지에서 체크박스, 오류메세지 등 프레임 오류를 수정완료 했습니다.
화이팅~

:sparkles:마이페이지 프레임작업중

---

server/src/main/generated/togedog/server/domain/member/mapper/MemberMapperImpl.java
server/src/test/java/togedog/server/MemberControllerTest.java

✨feat: email 기능 추가

---

server/src/main/java/togedog/server/domain/feed/controller/FeedController.java
server/src/main/java/togedog/server/domain/feed/entity/Feed.java
server/src/main/java/togedog/server/domain/feed/repository/FeedRepository.java
server/src/main/java/togedog/server/domain/feed/service/FeedService.java
server/src/main/java/togedog/server/domain/feed/service/dto/response/FeedResponse.java

✨ : Feed CRUD 기능추가 #38

---

.idea/TOGEDOG.iml
.idea/compiler.xml
.idea/gradle.xml
.idea/misc.xml
server/src/main/java/togedog/server/domain/feed/controller/FeedController.java
server/src/main/java/togedog/server/domain/feed/service/FeedService.java
server/src/main/java/togedog/server/domain/feed/service/dto/response/FeedResponse.java
server/src/main/java/togedog/server/domain/feedbookmark/entity/FeedBookmark.java
server/src/main/java/togedog/server/domain/feedbookmark/repository/FeedBookmarkRepository.java
server/src/main/java/togedog/server/domain/feedbookmark/service/FeedBookmarkService.java
server/src/main/java/togedog/server/domain/feedlike/entity/FeedLike.java
server/src/main/java/togedog/server/domain/feedlike/repository/FeedLikeRepository.java
server/src/main/java/togedog/server/global/entity/TypeEnum.java

- 신고 기능 빼고 일단 feed 기능은 완료 했습니다.

Feed CRUD 기능추가2 #38

---

client/src/components/myPage/MyFeedForm.style.tsx
client/src/components/myPage/feedCardComponent/FeedCard.style.tsx

좋아요,북마크 아이콘 변경

---

client/src/components/loginElement/LoginForm.tsx
client/src/components/signUpElement/SignUpInputs.tsx

로그인,회원가입 버튼 기능 구현중입니다.
- ngrok 이라 계속 변경될 예쩡
axios 통신 주말내로 services 로 옮겨놓고 해영님이랑 회의하고 완성시켜놓겠습니다...(최대한)

:sparkles:로그인,회원가입 버튼기능 구현중

---

.idea/compiler.xml
server/src/main/java/togedog/server/domain/chat/controller/MessageController.java
server/src/main/java/togedog/server/domain/chat/service/ChatService.java
server/src/main/java/togedog/server/domain/chat/service/MessageService.java
server/src/main/java/togedog/server/domain/chat/websocket/config/WebSocketConfig.java
server/src/main/java/togedog/server/domain/chat/websocket/connectlistener/WebSocketConnectListener.java
server/src/main/java/togedog/server/global/exception/businessexception/chatexception/ChatException.java
server/src/main/java/togedog/server/global/exception/businessexception/chatexception/ChatNotFoundException.java
server/src/main/resources/application-prod.yml

채팅 기능 로컬 테스트 끝내고 클라이언트와 테스트 대기중입니다!
- pub, sub 경로 수정
- 추후 읽음표시를 위한 EventListener 추가

:sparkles: feat: 채팅 기능 구현

---

.idea/modules.xml
.idea/modules/togedog.server.main.iml
server/build.gradle
server/src/main/java/togedog/server/domain/feed/controller/FeedController.java
server/src/main/java/togedog/server/domain/feed/service/FeedService.java
server/src/main/java/togedog/server/domain/feed/service/dto/request/FeedCreateServiceApiRequest.java
server/src/main/java/togedog/server/domain/reply/controller/ReplyController.java
server/src/main/java/togedog/server/domain/reply/controller/dto/ReplyCreateApiRequest.java
server/src/main/java/togedog/server/domain/reply/controller/dto/ReplyUpdateApiRequest.java
server/src/main/java/togedog/server/domain/reply/entity/Reply.java
server/src/main/java/togedog/server/domain/reply/service/ReplyService.java
server/src/main/java/togedog/server/domain/reply/service/dto/request/ReplyServiceCreateApiRequest.java
server/src/main/java/togedog/server/domain/reply/service/dto/request/ReplyServiceUpdateApiRequest.java
server/src/main/java/togedog/server/global/imageS3/S3Config.java
server/src/main/java/togedog/server/global/imageS3/S3Controller.java
server/src/main/java/togedog/server/global/imageS3/S3Service.java
server/src/main/resources/application-dev.yml

 ✨: reply crud및 s3 설정들

---

server/build.gradle
server/src/main/java/togedog/server/domain/feed/controller/FeedController.java
server/src/main/java/togedog/server/domain/feed/entity/Feed.java
server/src/main/java/togedog/server/domain/feed/service/FeedService.java
server/src/main/java/togedog/server/domain/feedbookmark/repository/FeedBookmarkRepository.java
server/src/main/java/togedog/server/domain/feedimage/entity/FeedImage.java
server/src/main/java/togedog/server/domain/feedlike/repository/FeedLikeRepository.java
server/src/main/java/togedog/server/domain/reply/controller/ReplyController.java
server/src/main/java/togedog/server/domain/reply/entity/Reply.java
server/src/main/java/togedog/server/domain/reply/service/ReplyService.java
server/src/main/java/togedog/server/domain/replylike/entity/ReplyLike.java
server/src/main/java/togedog/server/domain/replylike/repository/ReplyLikeRepository.java
server/src/main/java/togedog/server/domain/replylike/service/ReplyLikeService.java
server/src/main/java/togedog/server/global/imageS3/S3Config.java
server/src/main/java/togedog/server/global/imageS3/S3Controller.java
server/src/main/java/togedog/server/global/imageS3/S3Service.java
server/src/main/resources/application-dev.yml
server/src/main/resources/application-prod.yml

🐛 :jpa 매핑 및 aws 버그 수정

---

client/package-lock.json
client/package.json
client/src/components/chatting/ChattingContent.tsx
client/src/components/chatting/ChattingListForm.Style.tsx
client/src/components/chatting/ChattingListForm.tsx
client/src/components/chatting/ChattingLists.tsx
client/src/components/chatting/ContentListForm.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.Style.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/Upload.Style.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/Upload.tsx
client/src/components/petFeed/writingSpace/Map.tsx
client/src/components/petFeed/writingSpace/WritingSpace.tsx
client/src/services/chatService.tsx
client/src/services/feedService.tsx
client/src/types/feedDataType.tsx

프론트에서 프리사인드 url로 이미지와 영상 업로드를 위한 요청 로직 작성
채팅 기능 목업 작성
- 작성페이지에서 이미지와 영상 렌더링 ui변경
- 관련 api 서비스 작성

:sparkles: presinedUrl, chatting

---

client/src/components/loginElement/LoginForm.tsx
client/src/components/signUpElement/SignUpInputs.style.tsx
client/src/components/signUpElement/SignUpInputs.tsx
client/src/services/loginService.tsx
client/src/services/signUpService.tsx

axios 통신 service 파일로 이동
axios 통신 service 파일로 이동
토큰 받고 recoil 전역 상태 라이브러리 사용예정

:building_construction: axios 통신 폴더분리

---

client/src/components/chatting/ChattingDetail.tsx
client/src/components/chatting/ChattingLists.Style.tsx
client/src/components/chatting/ChattingLists.tsx
client/src/components/chatting/DetailForm.tsx
client/src/services/chatService.tsx
client/src/types/chatType.tsx

- 채팅 연결 구조 수정 및 시간 변경 로직 작성
- import {Stomp} -> import {Client}/ 로 활용하여 구현 방법 변경 - 연결 시도 진행 중
- timestamp 형식 유추하여 렌더링 시간 변경 로직 구현 (setTime)
- 불확정된 부분의 타입이나 api요청 기능 로직은 아직 정리 전입니다.
- 현재 들어가 있는 api요청 주소는 로컬서버 입니다.

:sparkles: feat: chatting

---

client/src/atoms/pagination/Pagination.tsx
client/src/pages/MapDetail.tsx

- 페이지네이션 임시 완료
- 페이지네이션 일단 완료했습니다.
- 한번 써보시고 원하시는 스타일 있으면 말씀주세요.
- Setting 드롭다운 이따 수정 조금 할 예정입니다.
- 추후 세부 디테일적인 기능들 추가해놓고, service 요청 로직 설정해놓겠습니다.

📱: 페이지네이션 임시 완료

---

client/src/App.tsx
client/src/atoms.tsx
client/src/components/loginElement/LoginForm.tsx
client/src/components/myPage/MyInfoForm.style.tsx
client/src/components/myPage/petProfile/component/Category.style.tsx
client/src/components/myPage/petProfile/component/Category.tsx
client/src/services/loginService.tsx
client/src/services/myPageService.tsx
client/src/types/myPageType.tsx

로컬스토리지 토큰저장, 상태관리 라이브러리 recoil추가
로컬스토리지 토큰저장, 상태관리 라이브러리 recoil추가
atoms.tsx 파일을 App.tsx와 동일한 위치에 생성했습니다. 따로 다른 폴더로 이동 원하시면 말씀 부탁,
atoms.tsx 에 주석처리로 사용방법? 을 주석 처리로 남겨놨습니다. 필요없으시다면 지우겠읍니다.
로그인 후 로컬스토리지에 토큰값 저장까진 되었고 토큰 디코딩은 수정후 내일 다시 pr올리겠습니다.
'npm install 하셔야 합니다.'

:sparkles:recoil 추가,로그인 서비스 토큰 저장 로직추가

---

server/src/main/java/togedog/server/domain/member/controller/MemberController.java
server/src/main/java/togedog/server/domain/member/service/MemberService.java
server/src/main/java/togedog/server/global/auth/config/SecurityConfig.java
server/src/main/java/togedog/server/global/auth/filter/JwtAuthenticationFilter.java
server/src/main/java/togedog/server/global/auth/utils/LoginMemberUtil.java
server/src/main/java/togedog/server/global/exception/businessexception/memberexception/MemberExistException.java
server/src/main/resources/application.yml

- LoginMemberUtil수정
- refresh토큰삭제
- SecurityConfig추가(주석처리)
- Exception추가

✨feat: LoginMemberUtil수정, refresh토큰삭제, SecurityConfig추가(주석처리), Exception추가

---

server/src/main/java/togedog/server/ServerApplication.java
server/src/main/java/togedog/server/domain/member/controller/MemberController.java
server/src/main/java/togedog/server/global/auth/filter/JwtAuthenticationFilter.java

✨ feat: JPA Auditing 추가

---

client/src/components/loginElement/LoginForm.tsx
client/src/components/signUpElement/SignUpInputs.tsx
client/src/services/loginService.tsx
client/src/services/signUpService.tsx

로컬 스토리지에 토큰저장을 완료했습니다.
로그인, 회원가입 자잘한 오류 해결했습니다.
로그인시 memberId를 header로 받고 로컬스토리지에 저장 예정입니다.

:bug:회원가입,로그인 오류 수정, 로컬스토리지 토큰저장완료

---

server/src/test/java/togedog/server/AlarmControllerTest.java

:truck: remove: Alarm 테스트코드 주석처리

---

client/src/components/chatting/ChattingLists.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.Style.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.tsx
client/src/components/petFeed/writingSpace/WritingSpace.tsx
client/src/components/petFeed/writingSpace/updatingSpace/UpdatingSpace.Style.tsx
client/src/components/petFeed/writingSpace/updatingSpace/UpdatingSpace.tsx
client/src/services/chatService.tsx

서버 통신 로직과 ui를 조금 변경했습니다
- 피드 작성에서 제목 유효성 로직 작성, 에디터 ui 조금 변경
- 피드 수정에서 제목, 내용 수정 로직 
- 채팅에서 채팅방 리스트 정보 받는 통신 로직 변경

:sparkles: feat: 피드 작성, 수정, 채팅 api 기능 로직 약간 수정

---

.github/workflows/main.yml
server/src/main/java/togedog/server/domain/chat/dto/ChatRoomResponse.java
server/src/main/java/togedog/server/domain/chat/entity/ChatRoom.java
server/src/main/java/togedog/server/domain/chat/mapper/ChatMapper.java
server/src/main/java/togedog/server/domain/chat/service/ChatService.java
server/src/main/java/togedog/server/domain/chat/service/MessageService.java

feat: cicd 수정 및 chat 추가 구현

---

.github/workflows/main.yml

docs: main.yml 수정

---

client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/Upload.tsx
client/src/components/petFeed/writingSpace/WritingSpace.tsx
client/src/components/petFeed/writingSpace/updatingSpace/UpdatingSpace.tsx
client/src/services/feedService.tsx
client/src/types/feedDataType.tsx

피드 작성 로직 완성 했습니다
- 피드 작성시 들어가는 제목, 내용, 이미지, 영상, 맵, 공개여부, 주소가 서버와 통신할 때 무리 없도록 로직 작성 완료 했습니다
- 영상과 이미지의 용량을 제한해서 받는 걸로 변경했습니다(영상 용량: 최대 50mb/ 이미지 용량: 장 당 최대 10mb)
- 프리사인드 로직 작성 했습니다
- 피드 작성 부분은 이미지와 영상이 잘 업로드만 이상 없이 되면 완성입니다.(이미지와 영상 사이즈를 어떻게 할까요)
- 이미지 크롭 에디터를 추가하는게 좋을까요?
- 피드 수정 부분에서 피드 개별 조회 정보 중 제목과 내용 정보 받아와야 해서 api서비스 작성 하셨다면 그걸로 get하겠습니다! 알려주세요~
- 지저분한 코드 정리 예정입니다.
- 채팅 부분은 소켓 연결 되고 난 이후에 더 진행 가능할 것 같습니다.
- 알림 부분도 통신 해 봐야 더 어떤식으로 진행할 수 있을지에 대한 답을 얻을 수 있을 것 같습니다.

✨ : 피드 작성 및 업데이트 부분

---

client/src/assets/images/icons/Circle.svg
client/src/atoms/pagination/Pagination.style.tsx
client/src/atoms/pagination/Pagination.tsx
client/src/atoms/pagination/PaginationCircle.tsx
client/src/components/petFeed/Feed.Style.tsx
client/src/components/petFeed/FeedDetail.tsx
client/src/components/petFeed/FeedList.tsx
client/src/components/petFeed/FeedReply.tsx
client/src/services/feedService.tsx
client/src/services/loginService.tsx

- 피드 이미지 기능 추가
- 피드 이미지 페이지네이션 기능 추가했습니다.
- 추후 이미지 확대 모달 만들고, service 및 hook 만들겠습니다.

피드 이미지 기능 추가

---

server/src/main/java/togedog/server/domain/chat/service/ChatService.java
server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java

:bug: fix: MapContent 및 ChatController 수정

---

client/src/components/petFeed/FeedDetail.tsx
client/src/components/petFeed/FeedImage.tsx
client/src/components/petFeed/FeedList.tsx

- 피드 확대 모달 생성
- 피드 이미지 눌렀을때 확대 이미지 모달 생성 했습니다.
- `none`

📱: 피드 확대 모달 생성

---

client/src/components/chatting/ChattingDetail.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/Upload.tsx
client/src/components/petFeed/writingSpace/Map.tsx
client/src/components/petFeed/writingSpace/WritingSpace.tsx
client/src/services/feedService.tsx
client/src/services/mapService.tsx
client/src/types/feedDataType.tsx
client/src/types/mapType.tsx

피드 작성 기능 완성
- 프리사인드 로직 완성
- 피드 등록 시 images/video data type변경
- 피드 등록 정보에서 map정보 분리 -> 피드 등록 직후에 맵에 좌표 보낼 수 있도록 변경
- 피드 등록 후 제목, 영상, 이미지, 공개 여부, 지도 연동 여부 등 조회까지 확인 되었습니다.
- 맵 좌표 등록 제외 입니다
- 코드 정리 전입니다..

:sparkles: feat: create feed complete, except enroll coordinate

---

server/src/main/java/togedog/server/domain/chat/entity/ChatParticipant.java
server/src/main/java/togedog/server/domain/chat/entity/Message.java
server/src/main/java/togedog/server/domain/mapcontent/entity/MapContent.java
server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java

MapContent 오류 수정

---

server/src/main/java/togedog/server/domain/comment/controller/dto/CommentCreateApiRequest.java
server/src/main/java/togedog/server/domain/mapcontent/entity/MapContent.java
server/src/main/java/togedog/server/domain/reply/controller/ReplyController.java

fix: MapCotent 및 CommentCreateApiRequest package 경로 수정

---

client/src/App.tsx
client/src/atoms.tsx
client/src/components/loginElement/LoginForm.tsx
client/src/components/signUpElement/SignUpInputs.tsx
client/src/components/userInfo/petProfile/PetProfileForm.tsx
client/src/hooks/memberHook.tsx
client/src/index.tsx
client/src/services/myPageService.tsx

Fe/feat/my page/#50

---

client/src/atoms.tsx
client/src/components/loginElement/LoginForm.tsx
client/src/components/modal/Modal.tsx
client/src/components/petFeed/CommentItems.tsx
client/src/components/petFeed/Feed.Style.tsx
client/src/components/petFeed/FeedComment.tsx
client/src/components/petFeed/FeedDetail.tsx
client/src/components/petFeed/FeedList.tsx
client/src/components/petFeed/FeedReply.tsx
client/src/components/signUpElement/SignUpInputs.tsx
client/src/hooks/CommentHook.ts
client/src/hooks/FeedHook.ts
client/src/hooks/ReplyHook.ts
client/src/services/commentService.tsx
client/src/services/feedService.tsx
client/src/services/replyService.tsx
client/src/types/feedDataType.tsx

- 댓글 CRUD 기능 완성
- 댓글 CRUD 기능 완성
- 대댓글 CR 기능 완성
- 금일 대댓글 남은 UD 기능 완성 마무리 하겠습니다.

댓글 CRUD 기능 완성

---

client/src/components/petFeed/writingSpace/WritingSpace.tsx
client/src/hooks/FeedHook.ts
client/src/services/chatService.tsx

:sparkles: feat: writing space 조금 수정

---

client/src/App.tsx
client/src/components/petFeed/FeedList.tsx
client/src/components/petFeed/writingSpace/WritingSpace.tsx
client/src/components/petFeed/writingSpace/updatingSpace/UpdatingSpace.Style.tsx
client/src/components/petFeed/writingSpace/updatingSpace/UpdatingSpace.tsx
client/src/hooks/FeedHook.ts
client/src/services/feedService.tsx

feed작성 비동기 작업 완료 해서 기능 동작 전부 완성으로 이상 없이 테스트 가능
feed수정 기능 피드 리스트 조회로부터 연결하기
- 피드 작성기능 요청 body값 이미지, 비디오 undefined-> 잘 들어감(WritingSpace.tsx)
문제 원인: handleInputChange함수의 이미지, 비디오 한정하여 동작하지 않음, setState함수 작동하지 않음
해결 방법: 통신 로직에는 promise체인을 걸었고 직접적으로 값 할당 -> api요청시 더 이상의 상태변화가 불필요 해서 일단 이렇게 처리 했습니다.
하지만 문제 원인에 대한 궁극적인 해결이 아니라서 더 알아봐야 할 것 같아요
같은 원리로 enrollCoordinate함수도 동작하지 않아 같은 방법으로 해결해서 좌표를 등록할 수 있도록 했습니다
- 피드 수정 기능 연결 했습니다(UpdatingSpace.tsx, WritingSpace)
1. useParams를 사용하여 해당 feedId값 추출해 연결
2. 수정페이지가 마운트 되면 피드 단일 조회로 기존의 제목, 내용, 이미지, 영상을 렌더링
3. WritingSpace로 해당 피드 id 전달하여 완료 버튼을 눌렀을 때 해당 피드의 id값으로 수정 api요청
종범님 피드 리스트 조회에서 비디오가 안나오고 있는데
스타일드 컴포넌트로 video쓰시는거면
import하는 곳에서 자식 요소로 source와 track이 필수로 있어야 합니다
제가 작성한 예시를 드리면
이렇게 video컴포넌트에 controls를 부여해주고
자식요소로 source와 track을 넣어 줬어요!
각각 통상적으로 쓰이는 …

:sparkles: feat: create feed기능 약간 수정/ update feed연결

---

server/build.gradle
server/src/main/generated/togedog/server/domain/member/mapper/MemberMapperImpl.java
server/src/main/java/togedog/server/global/redis/RedisConfig.java
server/src/main/java/togedog/server/global/redis/RedisUtil.java
server/src/main/resources/application-prod.yml
server/src/main/resources/application.yml

✨feat: 서버 업데이트(redis 수정2)

---

server/src/main/resources/application-prod.yml

✨feat: 업데이트

---

server/src/main/java/togedog/server/domain/chat/controller/ChatController.java
server/src/main/java/togedog/server/domain/chat/dto/ChatGetRequest.java
server/src/main/java/togedog/server/domain/chat/dto/ChatPostRequest.java
server/src/main/java/togedog/server/domain/chat/dto/ChatRoomResponse.java
server/src/main/java/togedog/server/domain/chat/dto/MessagePageResponse.java
server/src/main/java/togedog/server/domain/chat/dto/MessageRequest.java
server/src/main/java/togedog/server/domain/chat/dto/MessageResponse.java
server/src/main/java/togedog/server/domain/chat/entity/ChatParticipant.java
server/src/main/java/togedog/server/domain/chat/entity/ChatRoom.java
server/src/main/java/togedog/server/domain/chat/entity/Message.java

fix: chat 부분 수정

---

server/src/main/java/togedog/server/domain/chat/controller/ChatController.java
server/src/main/java/togedog/server/domain/chat/dto/ChatGetRequest.java
server/src/main/java/togedog/server/domain/chat/dto/ChatPostRequest.java
server/src/main/java/togedog/server/domain/chat/dto/ChatRoomResponse.java
server/src/main/java/togedog/server/domain/chat/dto/MessagePageResponse.java
server/src/main/java/togedog/server/domain/chat/dto/MessageRequest.java
server/src/main/java/togedog/server/domain/chat/dto/MessageResponse.java
server/src/main/java/togedog/server/domain/chat/entity/ChatParticipant.java
server/src/main/java/togedog/server/domain/chat/entity/ChatRoom.java
server/src/main/java/togedog/server/domain/chat/entity/Message.java
server/src/main/resources/application-prod.yml

12월25일 서버배포

---

.idea/compiler.xml
server/src/main/java/togedog/server/domain/chat/controller/ChatController.java

fix: chat get 요청 수정

---

server/src/main/java/togedog/server/domain/chat/mapper/ChatMapper.java

fix: chat get response 로직 수정

---

server/src/main/java/togedog/server/domain/chat/controller/ChatController.java
server/src/main/java/togedog/server/domain/chat/mapper/ChatMapper.java

12월25일 서버배포(chat get 로직 수정)

---

client/src/App.tsx
client/src/components/header/Header.tsx
client/src/components/modal/Modal.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/Upload.tsx
client/src/components/userInfo/UserFeedForm.tsx
client/src/components/userInfo/UserInfoForm.tsx
client/src/components/userInfo/infoChangeComponent/ProfileChange.tsx
client/src/components/userInfo/petComponent/PetAddForm.tsx
client/src/components/userInfo/petProfile/PetProfileForm.style.tsx
client/src/components/userInfo/petProfile/PetProfileForm.tsx
client/src/components/userInfo/petProfile/component/Category.tsx
client/src/hooks/UserInfoHook.ts
client/src/services/userInfoService.tsx
client/src/types/userInfoType.tsx

펫 프로필 수정하기 기능 구현,마이페이지 수정 기능 완
헤더 모달부분의 로그아웃탭/로그인탭 구분, 로그인상태에서 로고 클릭시 피드리스트 페이지로 이동
무한스크롤-oauth 작업예정

유저페이지 피드(무한스크롤)작업중

---

server/src/main/java/togedog/server/domain/chat/controller/ChatController.java
server/src/main/java/togedog/server/domain/chat/service/ChatService.java
server/src/main/java/togedog/server/domain/mapcontent/controller/MapContentController.java
server/src/main/java/togedog/server/domain/mapcontent/dto/MapContentFeedIdResponse.java
server/src/main/java/togedog/server/domain/mapcontent/dto/MapContentGetRequest.java
server/src/main/java/togedog/server/domain/mapcontent/entity/MapContent.java
server/src/main/java/togedog/server/domain/mapcontent/repository/MapContentRepository.java
server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java
server/src/main/java/togedog/server/global/exception/businessexception/mapcontentexception/MapContentException.java
server/src/main/java/togedog/server/global/exception/businessexception/mapcontentexception/MapContentNotFoundException.java

feat: mapContent 검색기능 및 chatRoom 삭제기능 추가

---

server/src/main/java/togedog/server/domain/chat/controller/ChatController.java
server/src/main/java/togedog/server/domain/chat/mapper/ChatMapper.java
server/src/main/java/togedog/server/domain/chat/service/ChatService.java
server/src/main/java/togedog/server/domain/mapcontent/controller/MapContentController.java
server/src/main/java/togedog/server/domain/mapcontent/dto/MapContentFeedIdResponse.java
server/src/main/java/togedog/server/domain/mapcontent/dto/MapContentGetRequest.java
server/src/main/java/togedog/server/domain/mapcontent/entity/MapContent.java
server/src/main/java/togedog/server/domain/mapcontent/repository/MapContentRepository.java
server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java
server/src/main/java/togedog/server/global/exception/businessexception/mapcontentexception/MapContentException.java
server/src/main/java/togedog/server/global/exception/businessexception/mapcontentexception/MapContentNotFoundException.java

[12월26일 배포] mapContent 좌표 검색기능 및 chatRoom 삭제기능 추가

---

client/src/App.tsx
client/src/atoms.tsx
client/src/atoms/modal/AlertModal.tsx
client/src/atoms/modal/ConfirmModal.tsx
client/src/atoms/modal/ReportModal.tsx
client/src/components/petFeed/Feed.Style.tsx
client/src/components/petFeed/FeedComment.tsx
client/src/components/petFeed/FeedDetail.tsx
client/src/components/petFeed/FeedList.tsx
client/src/components/petFeed/FeedReplies.tsx
client/src/components/petFeed/FeedReply.tsx
client/src/components/userInfo/petProfile/PetProfileForm.tsx
client/src/hooks/FeedHook.ts
client/src/hooks/MapHooks.ts
client/src/hooks/ReplyHook.ts
client/src/hooks/UserInfoHook.ts
client/src/services/mapService.tsx
client/src/types/mapType.tsx

- 댓글 무한스크롤
- 댓글 고정 기능
- 댓글 무한스크롤(더보기 버튼 클릭 시)
- 댓글 고정 기능 연결
- 펫지도 좌표 검색 훅 생성
- `none`

댓글 기능(무한스크롤, 고정) 생성

---

client/src/components/modal/Modal.tsx
client/src/components/petFeed/FeedList.tsx
client/src/components/signUpElement/SignUpInputs.tsx
client/src/components/userInfo/UserFeedForm.tsx
client/src/components/userInfo/UserInfoForm.tsx
client/src/components/userInfo/infoChangeComponent/ProfileChange.style.tsx
client/src/components/userInfo/infoChangeComponent/ProfileChange.tsx
client/src/components/userInfo/petComponent/PetAddForm.tsx
client/src/hooks/FeedHook.ts
client/src/hooks/UserInfoHook.ts
client/src/services/userInfoService.tsx
client/src/types/memberType.tsx

프리사인드 유저 프로필이미지 변경 기능
서버쪽 url만 완성되면 바로 사용 가능(테스트필요)
무한스크롤도 적용 완료 했습니다.

:sparkles:마이페이지 프로필이미지변경(서버만 완료되면 완성)

---

server/src/main/java/togedog/server/domain/mapcontent/controller/MapContentController.java
server/src/main/java/togedog/server/domain/mapcontent/dto/MapContentGetRequest.java
server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java

fix: mapContent 수정

---

server/src/main/java/togedog/server/domain/chat/controller/MessageController.java
server/src/main/java/togedog/server/domain/chat/mapper/MessageMapper.java
server/src/main/java/togedog/server/domain/chat/service/MessageService.java

fix: message response 수정

---

server/src/main/java/togedog/server/domain/chat/controller/ChatController.java
server/src/main/java/togedog/server/domain/chat/repository/MessageRepository.java
server/src/main/java/togedog/server/domain/chat/service/ChatService.java
server/src/main/java/togedog/server/global/exception/businessexception/chatexception/ChatBadRequestException.java

fix: chat 관련 오류 수정

---

server/src/main/java/togedog/server/domain/mapcontent/dto/MapContentGetRequest.java
server/src/main/java/togedog/server/domain/mapcontent/entity/MapContent.java
server/src/main/java/togedog/server/domain/mapcontent/repository/MapContentRepository.java
server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java

feat: 기준 범위내 피드 검색기능 구현

---

server/src/main/java/togedog/server/domain/mapcontent/dto/MapContentGetRequest.java
server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java

fix: mapcontent response 관련 수정

---

server/src/main/java/togedog/server/domain/feed/service/dto/response/FeedResponse.java
server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java

fix: mapContent Response에 좌표 추가

---

server/src/main/java/togedog/server/domain/feed/service/dto/response/FeedResponse.java
server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java

[배포]fix: mapContent Response에 좌표 추가

---

client/src/components/chatting/ChattingDetail.Style.tsx
client/src/components/chatting/ChattingDetail.tsx
client/src/components/chatting/ChattingForm.tsx
client/src/components/chatting/DetailForm.Style.tsx
client/src/components/chatting/DetailForm.tsx
client/src/components/chatting/UserImage.tsx
client/src/components/chatting/UserName.tsx
client/src/components/header/Header.Style.tsx
client/src/components/header/Header.tsx
client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.tsx
client/src/components/petFeed/writingSpace/WritingSpace.tsx
client/src/components/petFeed/writingSpace/updatingSpace/UpdatingSpace.Style.tsx
client/src/components/petFeed/writingSpace/updatingSpace/UpdatingSpace.tsx
client/src/hooks/ChatHooks.ts
client/src/hooks/FeedHook.ts
client/src/pages/Chatting.tsx
client/src/services/chatService.tsx
client/src/types/chatType.tsx

12/31테스트 기반 수정 

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/header/Header.tsx
client/src/components/loginElement/LoginForm.style.tsx
client/src/components/loginElement/Oauth.tsx
client/src/components/userInfo/UserFeedForm.style.tsx
client/src/components/userInfo/UserFeedForm.tsx
client/src/components/userInfo/infoChangeComponent/ProfileChange.style.tsx
client/src/components/userInfo/infoChangeComponent/ProfileChange.tsx
client/src/components/userInfo/petComponent/PetAddForm.tsx
client/src/components/userInfo/petProfile/PetProfileForm.tsx
client/src/hooks/MemberHook.ts
client/src/hooks/UserInfoHook.ts
client/src/index.tsx
client/src/services/userInfoService.tsx

마이페이지 버그수정 2차
회원가입시 닉네임 인증할때 중복 메세지띄움
[x] 회원가입시 이메일로 인증번호 전송 눌렀을때 이미 가입된 아이디인지 response 받기로함
[x] 펫 등록시 나이부분 숫자만 입력가능하게
[x] 자기 프로필,펫프로필 이미지 삭제 구현
[x] 게시물 없으면 아무것도 없다고 띄우기
[ ] 펫 등록후 바로 적용안됨(최초 1회만 안되고 그다음부터는 됨 캐싱 문제 의심중)
[ ] 2시간후 세션스토리지 초기화, 로그인 페이지로 이동 
구글 oauth 작업중,
리액트쿼리 어려웡

마이페이지 버그수정2차

---

client/src/atoms.tsx
client/src/atoms/pagination/Pagination.style.tsx
client/src/components/chatting/ChattingForm.tsx
client/src/components/petFeed/Feed.Style.tsx
client/src/components/petFeed/FeedDetail.tsx
client/src/components/petFeed/FeedList.tsx
client/src/components/petMap/MapFeedItem.tsx
client/src/components/petMap/PetMap.Style.tsx
client/src/hooks/MapHooks.ts
client/src/pages/PetFeed.tsx
client/src/pages/PetMap.tsx
client/src/services/mapService.tsx

- 2차 테스트 오류 수정사항 입니다.
<해결사항>
- 피드 전체 리스트에서 `<p>` 태그로 출력되는거 수정
- 댓글 더보기 버튼 => 데이터 없을땐 안뜨게 하기
- 모달창 있을 때, 스크롤 방지
- 피드의 맴버프로필을 누르면 맴버페이지로 가지게 하기
- 피드 리스트에서 프로필 형태 수정
- 펫맵 토글이랑 설정 드롭다운 z-index 값 수정
- 상세 피드에서 피드 동영상이나 이미지가 없을 경우 출력되는 것이 오류가 남
- 피드 전체 리스트에서 => 이미지 비디오 옆으로 스크롤 하는 버튼 작동 안함
- 펫지도 피드 리스트 item 미니미하게 만들어서 연결하기 + 핀마크 지도에 넣기
<오류사항>
- 댓글 및 대댓글에서 설정 버튼 누를 시 드롭다운에 의해 스크롤 발생 (CSS 설정)
- 추가적으로 작업하면서 계속 PR 올려놓겠습니다.
- `merge`는 하지 말아주세요!

🐛 : 1/1 2차 오류 수정, map 피드 리스트 조회 해야함.

---

server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java

mapcontent response 빈 배열 응답

---

server/src/main/java/togedog/server/domain/feed/service/dto/response/FeedResponse.java
server/src/main/java/togedog/server/domain/mapcontent/service/MapContentService.java

[배포]mapcontent response 빈 배열 응답

---

.idea/encodings.xml
server/src/main/generated/togedog/server/domain/member/mapper/MemberMapperImpl.java
server/src/main/generated/togedog/server/domain/pet/mapper/PetMapperImpl.java
server/src/main/java/togedog/server/domain/alarm/controller/AlarmController.java
server/src/main/java/togedog/server/domain/alarm/dto/AlarmResponse.java
server/src/main/java/togedog/server/domain/alarm/entity/Alarm.java
server/src/main/java/togedog/server/domain/alarm/mapper/AlarmMapper.java
server/src/main/java/togedog/server/domain/alarm/repository/AlarmRepository.java
server/src/main/java/togedog/server/domain/alarm/service/AlarmService.java
server/src/main/java/togedog/server/domain/comment/service/CommentService.java
server/src/main/java/togedog/server/domain/feedlike/service/FeedLikeService.java
server/src/main/java/togedog/server/domain/reply/service/ReplyService.java

feat: 알림 기능 추가

---

client/public/index.html
client/src/components/header/Header.Style.tsx
client/src/components/loginElement/LoginForm.style.tsx
client/src/components/petFeed/CommentItems.tsx
client/src/components/petFeed/Feed.Style.tsx
client/src/components/petFeed/FeedDetail.tsx
client/src/components/petFeed/FeedList.tsx
client/src/components/petFeed/FeedReply.tsx
client/src/components/petMap/MapFeedItem.tsx
client/src/pages/Login.tsx
client/src/pages/PetMap.tsx

- 4차 테스트 수정 했습니다.
- 대댓글 프로필 클릭 시 유저페이지 이동 연결했습니다
- 피드 상세 모달이 펫 맵 페이지에서 클릭 시 index 출력 오류를 수정했습니다. (헤더 컴포넌트가 더 위에 있던 오류)
- 다음 이슈로는 디자인하겠습닏.

📱  로그인 페이지 사이드 사진 첨부

---

server/src/main/java/togedog/server/domain/alarm/controller/AlarmController.java
server/src/main/java/togedog/server/domain/alarm/dto/AlarmResponse.java
server/src/main/java/togedog/server/domain/alarm/entity/Alarm.java
server/src/main/java/togedog/server/domain/alarm/mapper/AlarmMapper.java
server/src/main/java/togedog/server/domain/alarm/service/AlarmService.java
server/src/main/java/togedog/server/domain/chat/dto/ChatRoomResponse.java
server/src/main/java/togedog/server/domain/chat/mapper/ChatMapper.java
server/src/main/java/togedog/server/domain/chat/service/ChatService.java
server/src/main/java/togedog/server/domain/comment/service/CommentService.java
server/src/main/java/togedog/server/domain/feedlike/service/FeedLikeService.java
server/src/main/java/togedog/server/domain/reply/service/ReplyService.java

fix: 알림 response 수정 및 채팅방 목록 조회 시 최신 메세지 순으로 정렬하는 기능 추가

---

server/src/main/java/togedog/server/domain/alarm/controller/AlarmController.java
server/src/main/java/togedog/server/domain/alarm/dto/AlarmPageResponse.java
server/src/main/java/togedog/server/domain/alarm/mapper/AlarmMapper.java
server/src/main/java/togedog/server/domain/alarm/repository/AlarmRepository.java
server/src/main/java/togedog/server/domain/alarm/service/AlarmService.java

feat: alarm 조회 페이징 추가

---

client/src/App.tsx
client/src/atoms.tsx
client/src/components/chatting/ChattingList.Style.tsx
client/src/components/chatting/ChattingList.tsx
client/src/components/chatting/ChattingRoom.tsx
client/src/components/chatting/SearchUsers.Style.tsx
client/src/components/chatting/SearchUsers.tsx
client/src/components/chatting/UserImage.tsx
client/src/components/chatting/UserName.tsx
client/src/components/userInfo/UserInfoForm.tsx
client/src/hooks/ChatHooks.ts
client/src/index.css
client/src/services/chatService.tsx

-  유저페이지에서 채팅 연결하기
-  유저페이지 및 채팅 페이지에서 채팅방 생성하는 로직이 변경되었습니다
.

feat: 유저 페이지에서 메시지 클릭 시 채팅 연결

---

client/src/atoms.tsx
client/src/atoms/layout/Layout.style.tsx
client/src/atoms/modal/ConfirmModal.tsx
client/src/atoms/modal/Modal.style.tsx
client/src/atoms/modal/ReportModal.tsx
client/src/components/header/Header.Style.tsx
client/src/components/modal/Modal.Style.tsx
client/src/components/modal/setting/Setting.tsx
client/src/components/petFeed/Feed.Style.tsx
client/src/components/petFeed/FeedComment.tsx
client/src/components/petFeed/FeedDetail.style.ts
client/src/components/petFeed/FeedDetail.tsx
client/src/components/petFeed/FeedList.tsx
client/src/components/petFeed/FeedReplies.tsx
client/src/components/petFeed/FeedReply.style.ts
client/src/components/petFeed/FeedReply.tsx
client/src/components/petMap/MapFeedItem.tsx
client/src/components/petMap/PetMap.Style.tsx
client/src/components/userInfo/feedCardComponent/FeedCard.tsx
client/src/pages/PetMap.tsx

- 디자인 변경 후 남아 있는 오류사항들 수정했습니다.
- Setting Modal의 background 클릭 시 창 안닫히는 오류 수정
- Detail Modal에서 댓글 태그 추가 후 창을 닫고 다시 열었을 때, 댓글 태그가 그대로 존재하는 오류 수정
- PetMap 페이지 >> mapMode가 feed 일 때, 열고 접는 버튼 없어지는 오류 수정
- 댓글/대댓글 더보기 버튼 글자 색상 변경
- PetMap 페이지 >> detail Modal 열면 Header 하단에 랜더링 되는 문제를 수정
- Report Modal 디자인 수정
- 각 service에서 alert 코드 삭제 및 수정하기
- `none`

setting 오류 수정

---

client/src/atoms.tsx
client/src/atoms/layout/Layout.style.tsx
client/src/atoms/modal/ConfirmModal.tsx
client/src/atoms/modal/Modal.style.tsx
client/src/atoms/modal/ReportModal.tsx
client/src/components/header/Header.Style.tsx
client/src/components/modal/Modal.Style.tsx
client/src/components/modal/setting/Setting.tsx
client/src/components/petFeed/CommentItems.tsx
client/src/components/petFeed/Feed.Style.tsx
client/src/components/petFeed/FeedComment.tsx
client/src/components/petFeed/FeedDetail.style.ts
client/src/components/petFeed/FeedDetail.tsx
client/src/components/petFeed/FeedList.tsx
client/src/components/petFeed/FeedReplies.tsx
client/src/components/petFeed/FeedReply.style.ts
client/src/components/petFeed/FeedReply.tsx
client/src/components/petMap/MapFeed.style.ts
client/src/components/petMap/MapFeedItem.tsx
client/src/components/petMap/PetMap.Style.tsx
client/src/components/userInfo/feedCardComponent/FeedCard.tsx
client/src/hooks/CommentHook.ts
client/src/hooks/FeedHook.ts
client/src/hooks/MapHooks.ts
client/src/hooks/ReplyHook.ts
client/src/pages/PetFeed.tsx
client/src/pages/PetMap.tsx

- 반응형 디자인 추가 했습니다.
- 피드, 상세 피드, 펫맵 페이지 등 반응형 디자인 추가했습니다.
- `none`

반응형 디자인 추가

---

client/src/atoms/dropdown/DropDown.tsx

structure::드롭다운 오류 수정
